name: "Makefile: Package"

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: make deps
    - name: Run check
      run: make check
    - name: Package
      run: make package
